"""Add profile_picture to Specialist model

Revision ID: 8d6a000a7a0d
Revises: 1d780fc01fb7
Create Date: 2024-09-03 00:27:23.347448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6a000a7a0d'
down_revision = '1d780fc01fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('certifications')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
